version: '3.8'
services:
  backend:
    build: ./backend/app
    volumes:
      - ./backend/app:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: anysoft_demo
    ports:
      - "5432:5432"
    volumes:
      - ./data/seed_ecommerce.sql:/docker-entrypoint-initdb.d/seed_ecommerce.sql
      - ./data:/data 